spring.application.name=AlbumCollector

spring.datasource.url=jdbc:postgresql://YOURSERVER:YOURPORT/NAMEOFYOURDATABASE
spring.datasource.username=YOURUSERNAME
spring.datasource.password=YOURPASSWORD


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.profiles.active=user1